Ext.define('dmframe.view.dashboard.RightGrid', {
//    extend: 'Ext.view.View',
    extend: 'Ext.Component',
    xtype: 'dbrightgrid',
    tpl: [
        '<div class="colRight">',
        '<div class="conTitle">',
        '<div class="fl">',
        '<h2>주요 하자 현황<span class="count">(Total <em>10</em>건)</span></h2>',
        '</div>',
        '<div class="fr"><a href="#" class="more">더보기<em class="ico arr"></em></a></div>',
        '</div>',
        '<table class="basic" summary="주요 하자 현황표 - 현장코드,현장명,하자명, 요청공문발송, 착공계,준공계 순">',
        '<caption>주요 하자 현황 타이틀</caption>',
        '<colgroup><col style="width:48px"><col style="width:78px"><col style="width:130px"><col style="width:247px"><col style="width:115px"><col style="width:115px"><col style="width:*"></colgroup>',
        '<thead><tr><th>번호</th><th>현장코드</th><th>현장명</th><th>하자명</th><th>요청공문발송</th><th>착공계</th><th>준공계</th></tr></thead>',
        '</table>',
        '<div class="listWrap">',
        '<table class="basic" summary="주요 하자 현황표 - 현장코드,현장명,하자명, 요청공문발송, 착공계,준공계 순">',
        '<caption>주요 하자 현황 리스트</caption>',
        '<colgroup><col style="width:48px"><col style="width:78px"><col style="width:130px"><col style="width:247px"><col style="width:115px"><col style="width:115px"><col style="width:*"></colgroup>',
        '<tbody>',
        '<tr><td>1</td><td>025434</td><td>현장명 현장명6...</td><td class="txtL">하자명 하자명하자명 하자명하자명 하...</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>2</td><td>025434</td><td>현장명 현장명6...</td><td class="txtL">하자명 하자명하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>3</td><td>025434</td><td>현장명 현장명6...</td><td class="txtL">하자명 하자명하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>4</td><td>025434</td><td>현장명 현장명6...</td><td class="txtL">하자명 하자명하자명 하자명하자명 하...</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>5</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>6</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>7</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>8</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>9</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>10</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '<tr><td>11</td><td>025434</td><td>현장명현장명</td><td class="txtL">하자명 하자명</td><td>하자접수</td><td>2016.10.20</td><td>2016.10.20</td></tr>',
        '</tbody>',
        '</table>',
        '</div>',
        '</div>'
    ],
    data: {}
});
